import type { APIRoute } from "astro";
import { mediaFrom } from "@/lib/context";

export const prerender = false;

// Keys are generated by the upload endpoint; reject anything else.
const KEY_RE = /^posts\/[A-Za-z0-9._-]+$/;

/** Serve an uploaded image from the R2 `MEDIA` bucket. */
export const GET: APIRoute = async ({ params, request, locals }) => {
  const key = params.key ?? "";
  const bucket = mediaFrom(locals);
  if (!bucket || !KEY_RE.test(key)) return new Response("Not found", { status: 404 });

  const object = await bucket.get(key);
  if (!object) return new Response("Not found", { status: 404 });

  if (request.headers.get("If-None-Match") === object.httpEtag) {
    return new Response(null, { status: 304, headers: { ETag: object.httpEtag } });
  }
  return new Response(object.body, {
    headers: {
      "Content-Type": object.httpMetadata?.contentType ?? "application/octet-stream",
      "Cache-Control": "public, max-age=31536000, immutable",
      ETag: object.httpEtag,
      "X-Content-Type-Options": "nosniff",
    },
  });
};
